#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-07-02 
 */

use Net\Bazzline\Component\Cli\Autocomplete\Autocomplete;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Assembler;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Executable;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Validator;
use Net\Bazzline\Component\Cli\Autocomplete\Manager;
use Net\Bazzline\Component\Cli\Autocomplete\ManagerFactory;
use Net\Bazzline\Component\Cli\Autocomplete\ReadLine;

require_once __DIR__ . '/vendor/autoload.php';

$manager = new Manager();

class Demo
{
    public function bar()
    {
        $this->cli(__METHOD__, func_get_args());
    }
    public function foo()
    {
        $this->cli(__METHOD__, func_get_args());
    }

    private function cli($identifier, array $arguments = array())
    {
        fputs(STDOUT, 'called: ' . $identifier . ' with arguments: ' . var_export($arguments) . PHP_EOL);
    }
}

$demo = new Demo();

$dump = function ($arguments = null) {
    if (is_null($arguments)) {
        echo 'called without any arguments' . PHP_EOL;
    } else {
        var_dump($arguments);
    }
};

$configuration = array(
    'cli' => array(
        'bar' => array($demo, 'bar'),
        'foo' => array($demo, 'foo')
    ),
    'clear' => 'readline_clear_history',
    'echo'  => function ($arguments = null) {
        if (is_null($arguments)) {
            echo 'called without any arguments' . PHP_EOL;
        } else {
            echo var_export($arguments, true) . PHP_EOL;
        }
    },
    'dump'  => $dump
);

$factory    = new ManagerFactory();
$manager    = $factory->create();

$manager->setConfiguration($configuration);
$manager->setPrompt('example: ');
$manager->run();