#!/usr/bin/env php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-07-02 
 */

use Net\Bazzline\Component\Cli\Autocomplete\Autocomplete;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Assembler;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Executable;
use Net\Bazzline\Component\Cli\Autocomplete\Configuration\Validator;
use Net\Bazzline\Component\Cli\Autocomplete\Manager;

require_once __DIR__ . '/vendor/autoload.php';

$manager = new Manager();

class Demo
{
    public function bar()
    {
        $this->cli(__METHOD__, func_get_args());
    }
    public function foo()
    {
        $this->cli(__METHOD__, func_get_args());
    }

    private function cli($identifier, array $arguments = array())
    {
        fputs(STDOUT, 'called: ' . $identifier . ' with arguments: ' . var_export($arguments));
    }
}

$demo = new Demo();

$configuration = array(
    'cli' => array(
        'bar' => array($demo, 'bar'),
        'foo' => array($demo, 'foo')
    ),
    'clear' => 'readline_clear_history',
    'echo'  => 'var_export',
);

$assembler = new Assembler();

$assembler->setExecutable(new Executable());
$assembler->setValidator(new Validator());

$configuration = $assembler->assemble($configuration);

$manager->setAutocomplete(new Autocomplete());
$manager->setConfiguration($configuration);
$manager->run();