<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-05-27 
 */

namespace Net\Bazzline\Component\ApiDocumentBuilder\ProcessPipe;

use Net\Bazzline\Component\ProcessPipe\ExecutableInterface;
use Net\Bazzline\Component\ProcessPipe\Pipe;

class CreateNewProjectInTheCache extends Pipe
{
    public function pipe(ExecutableInterface $process, $_ = null)
    {
        /*
        $create = new Create();
        $create($pathToProjectCache);
        chdir($pathToProjectCache);
        $git->create($project['url'], '.');
        */
        return parent::pipe($process, $_); // TODO: Change the autogenerated stub
    }
}