<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-05-16 
 */

namespace Net\Bazzline\Component\Csv;

class EasyCsvWriterAdapter
{
    /** @var Writer|WriterForPhp5Dot3  */
    private $writer;

    /**
     * @param string $path
     * @param string $mode
     */
    public function __construct($path, $mode = 'r+')
    {
        $factory = new WriterFactory();
        $this->writer = $factory->create();
        $this->writer->setPath($path);
        //@todo what about mode?
    }

    public function setDelimiter($delimiter)
    {
        parent::setDelimiter($delimiter); // TODO: Change the autogenerated stub
    }

    public function setEnclosure($enclosure)
    {
        parent::setEnclosure($enclosure); // TODO: Change the autogenerated stub
    }

    public function writeRow($row)
    {
        return parent::writeRow($row); // TODO: Change the autogenerated stub
    }

    public function writeFromArray(array $array)
    {
        parent::writeFromArray($array); // TODO: Change the autogenerated stub
    }
}