<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2015-05-16 
 */

namespace Net\Bazzline\Component\Csv;

class EasyCsvWriterAdapter
{
    private $writer;

    public function __construct($path, $mode = 'r+')
    {
        parent::__construct($path, $mode); // TODO: Change the autogenerated stub
    }

    public function setDelimiter($delimiter)
    {
        parent::setDelimiter($delimiter); // TODO: Change the autogenerated stub
    }

    public function setEnclosure($enclosure)
    {
        parent::setEnclosure($enclosure); // TODO: Change the autogenerated stub
    }

    public function writeRow($row)
    {
        return parent::writeRow($row); // TODO: Change the autogenerated stub
    }

    public function writeFromArray(array $array)
    {
        parent::writeFromArray($array); // TODO: Change the autogenerated stub
    }
}