#!/bin/php
<?php
/**
 * @author stev leibelt <artodeto@bazzline.net>
 * @since 2014-07-31
 * @todo put it in nice classes
 */

$baseUrl                        = 'https://github.com/stevleibelt/incubator/tree/master/';
$filePath                       = __DIR__ . '/README.md';
$identifierOfSectionsAndIdeas   = '## Sections And Ideas';

//bo: update logic
function fetchContentThatShouldNotBeUpdated($identifier, $filePath)
{
    $contentOfReadme = explode("\n", file_get_contents($filePath));
    $contentBeforeIdentifier = array();

    foreach ($contentOfReadme as $content) {
        if ($content !== $identifier) {
            $contentBeforeIdentifier[] = $content;
        } else {
            break;
        }
    }

    return $contentBeforeIdentifier;
}

function createContentThatShouldBeUpdated(string $identifier, string $basePath, string $baseUrl) : array
{
    $content = [];

    $content[] = $identifier;
    $content[] = '';

    $fullQualifiedPathsWithFittingFiles = array();
    directoryWalker($basePath, $fullQualifiedPathsWithFittingFiles);

    $pathsAsArray = convertDirectoryWalkerResult($basePath, $fullQualifiedPathsWithFittingFiles);
    addGeneratedContent($content, $pathsAsArray, $baseUrl);

    return $content;
}

function addGeneratedContent(&$content, array $data, string $baseUrl)
{
    foreach ($data as $path => $fileName) {
        $lines = getLinesFromFile($path . DIRECTORY_SEPARATOR . $fileName, 1);
        $content[] = '* [' . substr($lines[0], 2) . '](' . $baseUrl . $path . ')';
    }
}

function convertDirectoryWalkerResult(string $basePath, array $array) : array
{
    $convertedArray = array();
    $lengthOfBasePath = strlen($basePath) + 1; //+1 for trailing directory slash

    foreach ($array as $fullQualifiedPath => $fileName) {
        $key = substr($fullQualifiedPath, $lengthOfBasePath);
        $convertedArray[$key] = $fileName;
    }

    return $convertedArray;
}

function directoryWalker(string $basePath, array &$array)
{
    $matchingSuffix = '.md';

    $directoryNames = getDirectoryNames($basePath);
    $subPathsToSearchIn = array();

    foreach ($directoryNames as $directoryName) {
        $foundMatchingSuffixInDirectory = false;
        $path = $basePath . DIRECTORY_SEPARATOR . $directoryName;
        $fileNames = getFileNames($path);

        foreach ($fileNames as $fileName) {
            if (stringEndsWith($fileName, $matchingSuffix)) {
                $array[$path] = $fileName;
                $foundMatchingSuffixInDirectory = true;
                break;
            }
        }

        if (!$foundMatchingSuffixInDirectory) {
            $subPathsToSearchIn[] = $path;
        }
    }

    foreach ($subPathsToSearchIn as $pathToSearchIn) {
        directoryWalker($pathToSearchIn, $array);
    }
}
//eo: update logic

//bo: file system utility
function getLinesFromFile(string $filePath, int $numberOfLines) : array
{
    $content = explode("\n", file_get_contents($filePath));
    $lines = array_slice($content, 0, $numberOfLines);

    return $lines;
}

function getFileNames(string $basePath) : array
{
    $names = [];

    if ($directoryHandle = opendir($basePath)) {
        while (false !== ($fileSystemIdentifier = readdir($directoryHandle))) {
            if (is_file($basePath . DIRECTORY_SEPARATOR . $fileSystemIdentifier)) {
                $names[] = $fileSystemIdentifier;
            }
        }
        closedir($directoryHandle);
    }

    return $names;
}

function getDirectoryNames(string $basePath) : array
{
    $names = [];

    if ($directoryHandle = opendir($basePath)) {
        $blacklistedDirectoryNames = [
            '.',
            '..',
            '.svn',
            '.git',
            '.idea',
            'vendor'
        ];
        while (false !== ($fileSystemIdentifier = readdir($directoryHandle))) {
            if (is_dir($basePath . DIRECTORY_SEPARATOR . $fileSystemIdentifier)) {
                if (!in_array($fileSystemIdentifier, $blacklistedDirectoryNames)) {
                    $names[] = $fileSystemIdentifier;
                }
            } else {
            }
        }
        closedir($directoryHandle);
    }

    return $names;
}
//eo: file system utility

//bo: string utility
function stringEndsWith(string $haystack, string $needle) : bool
{
    return (substr($haystack, -(strlen($needle))) === $needle);
}
//eo: string utility

//bo: generation
$content = array_merge(
    fetchContentThatShouldNotBeUpdated(
        $identifierOfSectionsAndIdeas,
        $filePath
    ),
    createContentThatShouldBeUpdated(
        $identifierOfSectionsAndIdeas,
        __DIR__,
        $baseUrl
    )
);

file_put_contents($filePath, implode("\n", $content));
//eo: generation
