#!/usr/bin/env php
<?php
/**
 * @author: stev leibelt <artodeto@bazzline.net>
 * @since: 2016-02-29
 */

use Net\Bazzline\Component\Cli\StandardStreams\InputOutputFactory;

require_once __DIR__ . '/../vendor/autoload.php';

$factory    = new InputOutputFactory();
$io         = $factory->createNewInstance();

$io->writeToOutput('simple write what you want and hit enter');

$content = $io->readFromInput();

$io->writeLineToOutput('read string with length of ' . strlen($content) . ' characters');
$io->writeToError('content was: ');
$io->writeLineToError('"' . $content . '"');
